---
title: "d3 Visualization - DrivenData"
author: "Marius Breitling"
date: "November 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Question: How is the distribution of the functional status of water pumps in Tanzania for specific regions?
First things first: Visualization might not work properly if just ran locally. Works when started on a (local) webserver though.


### Three datasources were introduced:
<ol>
<li>**trainDataPreRed.csv:** preprocessed version of a challenge offered by DrivenData, constisted of over
40 variables originally, was heavily reduced for sake of file size</li>
<li>**regionsInfo.json:** Information about regions in Tanzania. Created the file by the information given on https://en.wikipedia.org/wiki/Regions_of_Tanzania, just to give some background info for each clicked region.</li>
<li>**regions.geojson:** Path data for the map, features only contain the region names which are joined with the sources later on.
</ol>
### Possible interactions:
<ol>
<li>Levels of the categorical (target) variable 'status_group' can be hidden/shown by group by checking the respective box to get  of the overplotting.</li>
<li>by clicking on a specific region the following things should happen:
  <ol>
  <li>Region is colored in beige/yellow.</li>
  <li>Table in the right bottom corner is redrawn and offers some background
	information about the clicked region.</li>
  <li>Barchart in the upper right corner redraws and gives an overview of the
	distribution in the respective region.</li>
  </ol>
<li>A mouseover over a region colors it in red and shows the name of the region
in the bottom left corner in the same color.</li>
	




